name: CI

on:
  push:
    branches: main

jobs:
  test:
    name: test w/ Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install flit.
        run: pip install flit
      - name: Install dependencies.
        run: make install
      - name: Run unit tests with coverage.
        run: make test
